#include "a7106gpio.h"

void A7106_GPIO_init()
{
    SET_GPIO_OUT(CSCPROT);
    SET_GPIO_OUT(SCKPROT);
    SET_GPIO_OUT(SDIOPROT);
    SET_GPIO_OUT(CKOPROT);
    SET_GPIO_OUT(GIO1PROT); 
    SET_GPIO_OUT(GIO2PROT);
    
    SET_GPIO_H(CSCPROT);
    SET_GPIO_L(SCKPROT);
    SET_GPIO_H(SDIOPROT);
    SET_GPIO_H(CKOPROT);
    SET_GPIO_H(GIO1PROT);
    SET_GPIO_H(GIO2PROT);
}







